### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by davelab6** [vernnobile/OswaldFont#2]
- [ ] Family naming is messed up, Heavy -> ExtraBold, DemiBold -> SemiBold, family naming should follow the [Twardoch model](http://forum.fontlab.com/index.php?topic=313.0)
- [ ] nbsp advance width does not match the sp advance width
- [ ] italic angle not set in italic fonts
- [ ] Fonts don't roundtrip in ttx

``` sh
$ ttx Oswald-BoldItalic.ttf
Dumping "Oswald-BoldItalic.ttf" to "Oswald-BoldItalic.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'kern' table...
Traceback (most recent call last):
  File "/usr/local/bin/ttx", line 8, in <module>
    execfile(__file__)
  File "/Users/dcrossland/src/bakery-clean3/src/fonttools2/Tools/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "/Users/dcrossland/src/bakery-clean3/src/fonttools2/Lib/fontTools/ttx.py", line 332, in main
    process(jobs, options)
  File "/Users/dcrossland/src/bakery-clean3/src/fonttools2/Lib/fontTools/ttx.py", line 317, in process
    action(input, output, options)
  File "/Users/dcrossland/src/bakery-clean3/src/fonttools2/Lib/fontTools/ttx.py", line 208, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "/Users/dcrossland/src/bakery-clean3/src/fonttools2/Lib/fontTools/ttLib/__init__.py", line 275, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "/Users/dcrossland/src/bakery-clean3/src/fonttools2/Lib/fontTools/ttLib/__init__.py", line 312, in _tableToXML
    table.toXML(writer, self)
  File "/Users/dcrossland/src/bakery-clean3/src/fonttools2/Lib/fontTools/ttLib/tables/_k_e_r_n.py", line 67, in toXML
    subtable.toXML(writer, ttFont)
TypeError: toXML() takes exactly 2 arguments (3 given)
```

**Comment by vernnobile** [comment]
so much for DTL's OpenTypeManager :-(

**Comment by davelab6** [comment]
Well, it inspects the data, doesn't set these up does it?

**Comment by certainlyakey** [comment]
This caused major problems in Adobe apps, for example, a lot of italic fonts appeared under names of their regular versions. @bobtherobot [took the trouble](https://github.com/bobtherobot/OswaldFont) to clean it up, see his fork.
